name: sota
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  google_fonts: ^4.0.4
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  persistent_bottom_nav_bar: ^5.0.2
  animated_hint_textfield: ^1.0.1
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  form_validator: ^2.1.1
  get: 4.6.6
  flutter_rating_bar: ^4.0.1
  readmore: ^2.1.0
  flutter_dash: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

